"""empty message

Revision ID: 2968f5be650f
Revises: 53eee196ff8d
Create Date: 2021-07-27 17:28:29.315325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2968f5be650f'
down_revision = '53eee196ff8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_project_projectname'), 'project', ['projectname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_projectname'), table_name='project')
    # ### end Alembic commands ###
