"""empty message

Revision ID: 38aa7b3a5c02
Revises: 2968f5be650f
Create Date: 2021-07-27 17:29:14.690034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38aa7b3a5c02'
down_revision = '2968f5be650f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_projectname', table_name='project')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_project_projectname', 'project', ['projectname'], unique=False)
    # ### end Alembic commands ###
